export enum Status {
	ON_PROCESS = 1,
	FOR_SIGNING,
	FOR_RELEASE,
	CLAIMED,
	CANCELLED
}

export enum Course {
	INFORMATION_TECHNOLOGY = "IT",
	COMPUTER_SCIENCE = "CS",
	CIVIL_ENGINEERING = "CE",
	ELECTRICAL_ENGINEERING = "EE",
	PSYCHOLOGY = "PSY",
	BUSINESS_ADMINISTRATION = "BA",
	ACCOUNTANCY = "ACC",
	EDUCATION = "EDUC"
}

export enum StudentStatus {
	FIRST_YEAR = "FIRST_YEAR",
	SECOND_YEAR = "SECOND_YEAR",
	THIRD_YEAR = "THIRD_YEAR",
	FOURTH_YEAR = "FOURTH_YEAR",
	FIFTH_YEAR = "FIFTH_YEAR",
	IRREGULAR = "IRREGULAR",
	SHIFTEE = "SHIFTEE",
}

export enum Gender {
	MALE = 'M',
	FEMALE = 'F'
}
